import Link from 'next/link';
import Image from 'next/image';

export default function Footer() {
  return (
    <footer className="mt-auto bg-gradient-to-br from-[#2563EB] to-[#1e40af] text-blue-100">
      <div className="mx-auto max-w-6xl px-4 py-12">
        <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {/* Brand */}
          <div>
            <Link href="/" className="flex items-center gap-2.5">
              <Image
                src="/images/logo.png"
                alt="The Care Audit logo"
                width={32}
                height={32}
                className="h-8 w-auto drop-shadow-[0_1px_4px_rgba(255,255,255,0.2)]"
              />
              <span className="text-lg font-bold text-white" style={{ fontFamily: 'var(--font-heading)' }}>
                The Care Audit
              </span>
            </Link>
            <p className="mt-3 text-sm leading-relaxed text-blue-200">
              Assisted Living Facility inspection reports in plain English
              across all 50 states. Helping families make informed decisions.
            </p>
          </div>

          {/* Links */}
          <div>
            <h4 className="mb-3 text-sm font-semibold uppercase tracking-wider text-blue-200">
              Quick Links
            </h4>
            <ul className="space-y-2 text-sm">
              <li>
                <Link href="/" className="text-blue-100 transition-colors duration-200 hover:text-white">Home</Link>
              </li>
              <li>
                <Link href="/search" className="text-blue-100 transition-colors duration-200 hover:text-white">Search</Link>
              </li>
              <li>
                <Link href="/about" className="text-blue-100 transition-colors duration-200 hover:text-white">About</Link>
              </li>
              <li>
                <Link href="/contact" className="text-blue-100 transition-colors duration-200 hover:text-white">Contact</Link>
              </li>
              <li>
                <Link href="/for-facilities" className="text-blue-100 transition-colors duration-200 hover:text-white">For Facilities</Link>
              </li>
            </ul>
          </div>

          {/* Disclaimer */}
          <div>
            <h4 className="mb-3 text-sm font-semibold uppercase tracking-wider text-blue-200">
              Disclaimer
            </h4>
            <p className="text-sm leading-relaxed text-blue-200">
              Data sourced from official state health department inspection records.
              This site is not affiliated with any government agency. Facility
              summaries are generated by artificial intelligence and may contain
              errors or omissions. The Care Audit does not conduct inspections,
              assign ratings, or make recommendations. Information is provided
              for educational purposes only.
            </p>
          </div>
        </div>

        <div className="mt-10 border-t border-white/20 pt-6 text-center text-xs text-blue-200">
          &copy; {new Date().getFullYear()} The Care Audit. All rights reserved.
        </div>
      </div>
    </footer>
  );
}
