import { Phone, MapPin, Calendar } from 'lucide-react';
import Header from '@/components/Header';
import Breadcrumb from '@/components/Breadcrumb';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Demo: Facility Response | The Care Audit',
  description: 'See what a Facility Response looks like on The Care Audit — your official response, posted directly below the inspection data.',
  robots: { index: false, follow: false },
};

export default function FacilityResponseDemoPage() {
  return (
    <div className="flex min-h-screen flex-col bg-warm-50">
      <Header />
      <main className="mx-auto w-full max-w-4xl flex-1 px-4 py-8">

        <Breadcrumb
          items={[
            { label: 'Home', href: '/' },
            { label: 'Tennessee', href: '/tennessee' },
            { label: 'Memphis', href: '/tennessee/memphis' },
            { label: 'Sunrise Care Center' },
          ]}
        />

        {/* Facility Header */}
        <div className="mt-6 rounded-2xl border border-warm-200 bg-white p-6 shadow-sm">
          <div className="flex flex-wrap items-start gap-3">
            <h1 className="text-3xl font-bold text-gray-900" style={{ fontFamily: 'var(--font-heading)' }}>
              Sunrise Care Center
            </h1>
          </div>
          <p className="mt-2 flex items-center gap-1.5 text-gray-500">
            <MapPin className="h-4 w-4 shrink-0" />
            4210 Willow Creek Blvd, Memphis, Tennessee 38116
          </p>
          <p className="mt-1 flex items-center gap-1.5 text-sm text-gray-500">
            <Phone className="h-4 w-4 shrink-0" />
            (901) 555-0247
          </p>
          <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-gray-500">
            <span>Assisted Living Facility</span>
            <span className="text-gray-300">|</span>
            <span className="flex items-center gap-1"><Calendar className="h-3.5 w-3.5" />Last inspected January 9, 2025</span>
          </div>
          <p className="mt-2 text-xs text-gray-400">
            Inspection data is sourced from official state health department portals and refreshed on a rolling schedule.
          </p>
        </div>

        {/* Top CTA */}
        <div className="mt-6 rounded-2xl border border-warm-200 bg-white p-6 shadow-sm text-center">
          <p className="text-sm text-gray-500 mb-4">This is a demo of the <strong>Facility Response</strong> tier ($49/mo). Add your official response — it appears here, directly below the inspection data, where families are reading.</p>
          <a
            href="/for-facilities"
            className="inline-flex items-center gap-2 rounded-xl bg-navy px-6 py-3.5 font-semibold text-white shadow-sm transition-all hover:bg-navy-light hover:shadow-md"
          >
            Add your response — 7-day free trial
          </a>
        </div>

        {/* Violation Summary */}
        <div className="mt-8 rounded-2xl border border-warm-200 bg-white p-8 shadow-sm">
          <div className="flex flex-col items-center text-center">
            <p className="text-xl font-semibold text-gray-800">7 violations cited</p>
            <div className="mt-3 flex flex-wrap items-center justify-center gap-x-4 gap-y-1 text-sm text-gray-500">
              <span>Last inspected: January 9, 2025</span>
              <span className="text-gray-300">|</span>
              <span>Licensed for 62 beds</span>
            </div>
          </div>
        </div>

        {/* AI Summary */}
        <div className="mt-8 rounded-2xl border border-warm-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-gray-900" style={{ fontFamily: 'var(--font-heading)' }}>
            AI-Generated Summary
          </h2>
          <p className="mt-2 leading-relaxed text-gray-700">
            Sunrise Care Center has 7 violations cited on its most recent state inspection. The facility is licensed for 62 residents in Memphis, Tennessee. Inspection records show citations in the areas of staffing documentation, medication administration, and resident care planning. The facility has been operating under state licensure in Tennessee.
          </p>
          <p className="mt-2 text-xs text-gray-400">
            AI-generated summary &copy; {new Date().getFullYear()} ConvoLogic LLC / The Care Audit. Unauthorized reproduction prohibited.
          </p>
          <p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs leading-relaxed text-amber-800">
            ⚠️ This summary was generated by artificial intelligence based on official state inspection reports. It may contain errors or omissions. It is not a professional assessment and should not be the sole basis for any decision. Always refer to the official inspection report for complete and authoritative information.
          </p>
        </div>

        {/* Official Facility Response */}
        <div className="mt-8 rounded-2xl border border-blue-200 bg-blue-50/50 p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-gray-900" style={{ fontFamily: 'var(--font-heading)' }}>
            Official Facility Response
          </h2>
          <p className="mt-2 leading-relaxed text-gray-700">
            We take every citation seriously. Following our January 2025 inspection, we implemented a comprehensive staff training protocol and an updated medication management process reviewed by our medical director. Our current compliance rate is 98% as of our most recent internal audit. We welcome families to tour our facility and speak with our staff directly about the improvements we have made.
          </p>
          <p className="mt-4 text-xs text-gray-500">
            This response was provided by the facility and does not represent the views of The Care Audit.
          </p>
        </div>

        {/* Bottom CTA */}
        <div className="mt-8 rounded-2xl border border-warm-200 bg-white p-6 shadow-sm text-center">
          <p className="text-sm text-gray-500 mb-4">Your response appears here — directly below the inspection data, where families are making decisions about care.</p>
          <a
            href="/for-facilities"
            className="inline-flex items-center gap-2 rounded-xl bg-navy px-6 py-3.5 font-semibold text-white shadow-sm transition-all hover:bg-navy-light hover:shadow-md"
          >
            Add your response — 7-day free trial
          </a>
          <p className="mt-3 text-xs text-gray-400">7-day free trial. Card required. Cancel anytime.</p>
        </div>

      </main>
      <Footer />
    </div>
  );
}
